version: 0.2

phases:
  install:
    runtime-versions:
      buildtools: [cmake]
      # Include other build tools if necessary (e.g., gcc, clang)
    commands:
      - echo Installing dependencies...
      - apt-get update
      - apt-get install -y g++ make

  pre_build:
    commands:
      - echo Starting pre-build phase...

  build:
    commands:
      - echo Building the project...
      - cmake .
      - cmake --build .

  post_build:
    commands:
      - echo Build completed.

artifacts:
  files:
    - '**/*'
  discard-paths: no
