version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies...
      - apt-get update
      - apt-get install -y cmake g++ make

  pre_build:
    commands:
      - echo Starting pre-build phase...

  build:
    commands:
      - echo Building the project...
      - cmake .
      - cmake --build .

  post_build:
    commands:
      - echo Build completed.

artifacts:
  files:
    - '**/*'
  discard-paths: no
